export const DEMO_RECORDS = [
  {
    test_id: 'TEST-DEMO-0007',
    operator_id: 'DEMO-OPERATOR-003',
    timestamp: '2026-09-17T10:42:11Z',
    test_type: 'COLORIMETRIC',
    result: 'INCONCLUSIVE',
    confidence: null,
    sync_status: 'SYNCED',
    integrity_status: 'VERIFIED',
  },
  {
    test_id: 'TEST-DEMO-0006',
    operator_id: 'DEMO-OPERATOR-001',
    timestamp: '2026-09-17T09:18:43Z',
    test_type: 'COLORIMETRIC',
    result: 'PRESUMPTIVE_NEGATIVE',
    confidence: 0.87,
    sync_status: 'SYNCED',
    integrity_status: 'VERIFIED',
  },
  {
    test_id: 'TEST-DEMO-0005',
    operator_id: 'DEMO-OPERATOR-002',
    timestamp: '2026-09-16T16:31:02Z',
    test_type: 'COLORIMETRIC',
    result: 'INCONCLUSIVE',
    confidence: null,
    sync_status: 'QUEUED',
    integrity_status: 'UNVERIFIED',
  },
  {
    test_id: 'TEST-DEMO-0004',
    operator_id: 'DEMO-OPERATOR-004',
    timestamp: '2026-09-16T13:07:28Z',
    test_type: 'COLORIMETRIC',
    result: 'PRESUMPTIVE_POSITIVE',
    confidence: 0.91,
    sync_status: 'SYNCED',
    integrity_status: 'VERIFIED',
  },
];
